BicingStats\Domain\Model\Station\StationState:
    type: entity
    repositoryClass: BicingStats\Bundle\MainBundle\Repository\StationStateRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        statusCode:
            type: string
        availableBikes:
            type: integer
        time:
            type: datetime
        freeSlots:
            type: integer
    manyToOne:
        station:
            targetEntity: BicingStats\Domain\Model\Station\Station
